#!/bin/bash
#
#===================================================
#Description:
#This script must be at the same place your ARIA file (.xml) that will be used for structure calculation
#
#Authors: Santos, BPO; Quezado, MTQ.
#Institution: LBM, UFMG, Brazil
#
#Before usage, type on linux shell:
#	chmod +x run_patches
#
#Mode of use:
#	run_patches <structurecalculation_folder_name> <N or C or NC>
#
#===================================================

#Parameters that will be modficated in any conditions:
topdir=${1:-.}

modx=$2

cp /usr/local/bin/peptide_modification/topallhdg5.3.pro "$topdir"/run1/cns/toppar/
cp /usr/local/bin/peptide_modification/parallhdg5.3.pro "$topdir"/run1/cns/toppar/

#===================================================

#N-terminal Acetylation
if [[ $modx == "N" ]]; then
    cp /usr/local/bin/peptide_modification/n_term_acet/topallhdg5.3.pep "$topdir"/run1/cns/toppar/
fi

#C-terminal Amidation
if [[ $modx == "C" ]]; then
    cp /usr/local/bin/peptide_modification/c_term_amid/topallhdg5.3.pep "$topdir"/run1/cns/toppar/
fi

#N-terminal and C-terminal modifications
if [[ $modx == "NC" ]]; then
    cp /usr/local/bin/peptide_modification/n_term_c_term/topallhdg5.3.pep "$topdir"/run1/cns/toppar/
fi
